/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.assa.sm.parser.antlr;

import com.google.inject.Inject;
import dk.sdu.mmmi.assa.sm.parser.antlr.internal.InternalStateMachineParser;
import dk.sdu.mmmi.assa.sm.services.StateMachineGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class StateMachineParser extends AbstractAntlrParser {

	@Inject
	private StateMachineGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalStateMachineParser createParser(XtextTokenStream stream) {
		return new InternalStateMachineParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Root";
	}

	public StateMachineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StateMachineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
