/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.assa.sm.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import dk.sdu.mmmi.assa.sm.ide.contentassist.antlr.internal.InternalStateMachineParser;
import dk.sdu.mmmi.assa.sm.services.StateMachineGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class StateMachineParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(StateMachineGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, StateMachineGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getMachineAccess().getAlternatives_3(), "rule__Machine__Alternatives_3");
			builder.put(grammarAccess.getRootAccess().getGroup(), "rule__Root__Group__0");
			builder.put(grammarAccess.getMachineAccess().getGroup(), "rule__Machine__Group__0");
			builder.put(grammarAccess.getStateAccess().getGroup(), "rule__State__Group__0");
			builder.put(grammarAccess.getStateAccess().getGroup_3(), "rule__State__Group_3__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup(), "rule__Transition__Group__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_3(), "rule__Transition__Group_3__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_4(), "rule__Transition__Group_4__0");
			builder.put(grammarAccess.getTransitionAccess().getGroup_5(), "rule__Transition__Group_5__0");
			builder.put(grammarAccess.getFloatAccess().getGroup(), "rule__Float__Group__0");
			builder.put(grammarAccess.getFloatAccess().getGroup_1(), "rule__Float__Group_1__0");
			builder.put(grammarAccess.getRootAccess().getNameAssignment_1(), "rule__Root__NameAssignment_1");
			builder.put(grammarAccess.getRootAccess().getMachineAssignment_2(), "rule__Root__MachineAssignment_2");
			builder.put(grammarAccess.getMachineAccess().getNameAssignment_1(), "rule__Machine__NameAssignment_1");
			builder.put(grammarAccess.getMachineAccess().getStatesAssignment_3_0(), "rule__Machine__StatesAssignment_3_0");
			builder.put(grammarAccess.getMachineAccess().getTransitionsAssignment_3_1(), "rule__Machine__TransitionsAssignment_3_1");
			builder.put(grammarAccess.getStateAccess().getFailAssignment_0(), "rule__State__FailAssignment_0");
			builder.put(grammarAccess.getStateAccess().getNameAssignment_2(), "rule__State__NameAssignment_2");
			builder.put(grammarAccess.getStateAccess().getMachineAssignment_3_1(), "rule__State__MachineAssignment_3_1");
			builder.put(grammarAccess.getTransitionAccess().getFromAssignment_0(), "rule__Transition__FromAssignment_0");
			builder.put(grammarAccess.getTransitionAccess().getToAssignment_2(), "rule__Transition__ToAssignment_2");
			builder.put(grammarAccess.getTransitionAccess().getWhenAssignment_3_1(), "rule__Transition__WhenAssignment_3_1");
			builder.put(grammarAccess.getTransitionAccess().getTimeAssignment_4_0(), "rule__Transition__TimeAssignment_4_0");
			builder.put(grammarAccess.getTransitionAccess().getTimeoutAssignment_4_1(), "rule__Transition__TimeoutAssignment_4_1");
			builder.put(grammarAccess.getTransitionAccess().getSignalAssignment_5_1(), "rule__Transition__SignalAssignment_5_1");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private StateMachineGrammarAccess grammarAccess;

	@Override
	protected InternalStateMachineParser createParser() {
		InternalStateMachineParser result = new InternalStateMachineParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public StateMachineGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(StateMachineGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
