/*
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.assa.sm.ui.tests;

import com.google.inject.Injector;
import dk.sdu.mmmi.assa.sm.ui.internal.SmActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class StateMachineUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return SmActivator.getInstance().getInjector("dk.sdu.mmmi.assa.sm.StateMachine");
	}

}
