/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.assa.sm.stateMachine;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Max Execution Time</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see dk.sdu.mmmi.assa.sm.stateMachine.StateMachinePackage#getMaxExecutionTime()
 * @model
 * @generated
 */
public interface MaxExecutionTime extends SafetyProperty
{
} // MaxExecutionTime
