/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.assa.sm.stateMachine;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see dk.sdu.mmmi.assa.sm.stateMachine.StateMachineFactory
 * @model kind="package"
 * @generated
 */
public interface StateMachinePackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "stateMachine";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.sdu.dk/mmmi/assa/sm/StateMachine";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "stateMachine";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  StateMachinePackage eINSTANCE = dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl.init();

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.RootImpl <em>Root</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.RootImpl
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getRoot()
   * @generated
   */
  int ROOT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__NAME = 0;

  /**
   * The feature id for the '<em><b>Machines</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT__MACHINES = 1;

  /**
   * The number of structural features of the '<em>Root</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROOT_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.MachineImpl <em>Machine</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.MachineImpl
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getMachine()
   * @generated
   */
  int MACHINE = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__NAME = 0;

  /**
   * The feature id for the '<em><b>States</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__STATES = 1;

  /**
   * The feature id for the '<em><b>Transitions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE__TRANSITIONS = 2;

  /**
   * The number of structural features of the '<em>Machine</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MACHINE_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.StateImpl <em>State</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateImpl
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getState()
   * @generated
   */
  int STATE = 2;

  /**
   * The feature id for the '<em><b>Fail</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__FAIL = 0;

  /**
   * The feature id for the '<em><b>End</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__END = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__NAME = 2;

  /**
   * The feature id for the '<em><b>Machine</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE__MACHINE = 3;

  /**
   * The number of structural features of the '<em>State</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int STATE_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.TransitionImpl <em>Transition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.TransitionImpl
   * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getTransition()
   * @generated
   */
  int TRANSITION = 3;

  /**
   * The feature id for the '<em><b>From</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__FROM = 0;

  /**
   * The feature id for the '<em><b>To</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TO = 1;

  /**
   * The feature id for the '<em><b>Has Guard</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__HAS_GUARD = 2;

  /**
   * The feature id for the '<em><b>Guard</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__GUARD = 3;

  /**
   * The feature id for the '<em><b>Has When</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__HAS_WHEN = 4;

  /**
   * The feature id for the '<em><b>When</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__WHEN = 5;

  /**
   * The feature id for the '<em><b>Time</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TIME = 6;

  /**
   * The feature id for the '<em><b>Timeout</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__TIMEOUT = 7;

  /**
   * The feature id for the '<em><b>Has Signal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__HAS_SIGNAL = 8;

  /**
   * The feature id for the '<em><b>Signal</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION__SIGNAL = 9;

  /**
   * The number of structural features of the '<em>Transition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TRANSITION_FEATURE_COUNT = 10;


  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.assa.sm.stateMachine.Root <em>Root</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Root</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Root
   * @generated
   */
  EClass getRoot();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Root#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Root#getName()
   * @see #getRoot()
   * @generated
   */
  EAttribute getRoot_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.assa.sm.stateMachine.Root#getMachines <em>Machines</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Machines</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Root#getMachines()
   * @see #getRoot()
   * @generated
   */
  EReference getRoot_Machines();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.assa.sm.stateMachine.Machine <em>Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Machine</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Machine
   * @generated
   */
  EClass getMachine();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Machine#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Machine#getName()
   * @see #getMachine()
   * @generated
   */
  EAttribute getMachine_Name();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.assa.sm.stateMachine.Machine#getStates <em>States</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>States</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Machine#getStates()
   * @see #getMachine()
   * @generated
   */
  EReference getMachine_States();

  /**
   * Returns the meta object for the containment reference list '{@link dk.sdu.mmmi.assa.sm.stateMachine.Machine#getTransitions <em>Transitions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Transitions</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Machine#getTransitions()
   * @see #getMachine()
   * @generated
   */
  EReference getMachine_Transitions();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.assa.sm.stateMachine.State <em>State</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>State</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.State
   * @generated
   */
  EClass getState();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.State#isFail <em>Fail</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fail</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.State#isFail()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Fail();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.State#isEnd <em>End</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>End</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.State#isEnd()
   * @see #getState()
   * @generated
   */
  EAttribute getState_End();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.State#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.State#getName()
   * @see #getState()
   * @generated
   */
  EAttribute getState_Name();

  /**
   * Returns the meta object for the containment reference '{@link dk.sdu.mmmi.assa.sm.stateMachine.State#getMachine <em>Machine</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Machine</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.State#getMachine()
   * @see #getState()
   * @generated
   */
  EReference getState_Machine();

  /**
   * Returns the meta object for class '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition <em>Transition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Transition</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition
   * @generated
   */
  EClass getTransition();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#getFrom <em>From</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>From</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#getFrom()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_From();

  /**
   * Returns the meta object for the reference '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#getTo <em>To</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>To</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#getTo()
   * @see #getTransition()
   * @generated
   */
  EReference getTransition_To();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#isHasGuard <em>Has Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has Guard</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#isHasGuard()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_HasGuard();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#isGuard <em>Guard</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Guard</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#isGuard()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Guard();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#isHasWhen <em>Has When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has When</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#isHasWhen()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_HasWhen();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#getWhen <em>When</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>When</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#getWhen()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_When();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#isTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Time</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#isTime()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Time();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#getTimeout <em>Timeout</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Timeout</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#getTimeout()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Timeout();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#isHasSignal <em>Has Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Has Signal</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#isHasSignal()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_HasSignal();

  /**
   * Returns the meta object for the attribute '{@link dk.sdu.mmmi.assa.sm.stateMachine.Transition#getSignal <em>Signal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Signal</em>'.
   * @see dk.sdu.mmmi.assa.sm.stateMachine.Transition#getSignal()
   * @see #getTransition()
   * @generated
   */
  EAttribute getTransition_Signal();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  StateMachineFactory getStateMachineFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.RootImpl <em>Root</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.RootImpl
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getRoot()
     * @generated
     */
    EClass ROOT = eINSTANCE.getRoot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROOT__NAME = eINSTANCE.getRoot_Name();

    /**
     * The meta object literal for the '<em><b>Machines</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROOT__MACHINES = eINSTANCE.getRoot_Machines();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.MachineImpl <em>Machine</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.MachineImpl
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getMachine()
     * @generated
     */
    EClass MACHINE = eINSTANCE.getMachine();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MACHINE__NAME = eINSTANCE.getMachine_Name();

    /**
     * The meta object literal for the '<em><b>States</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MACHINE__STATES = eINSTANCE.getMachine_States();

    /**
     * The meta object literal for the '<em><b>Transitions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MACHINE__TRANSITIONS = eINSTANCE.getMachine_Transitions();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.StateImpl <em>State</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateImpl
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getState()
     * @generated
     */
    EClass STATE = eINSTANCE.getState();

    /**
     * The meta object literal for the '<em><b>Fail</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__FAIL = eINSTANCE.getState_Fail();

    /**
     * The meta object literal for the '<em><b>End</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__END = eINSTANCE.getState_End();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute STATE__NAME = eINSTANCE.getState_Name();

    /**
     * The meta object literal for the '<em><b>Machine</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference STATE__MACHINE = eINSTANCE.getState_Machine();

    /**
     * The meta object literal for the '{@link dk.sdu.mmmi.assa.sm.stateMachine.impl.TransitionImpl <em>Transition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.TransitionImpl
     * @see dk.sdu.mmmi.assa.sm.stateMachine.impl.StateMachinePackageImpl#getTransition()
     * @generated
     */
    EClass TRANSITION = eINSTANCE.getTransition();

    /**
     * The meta object literal for the '<em><b>From</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__FROM = eINSTANCE.getTransition_From();

    /**
     * The meta object literal for the '<em><b>To</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference TRANSITION__TO = eINSTANCE.getTransition_To();

    /**
     * The meta object literal for the '<em><b>Has Guard</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__HAS_GUARD = eINSTANCE.getTransition_HasGuard();

    /**
     * The meta object literal for the '<em><b>Guard</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__GUARD = eINSTANCE.getTransition_Guard();

    /**
     * The meta object literal for the '<em><b>Has When</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__HAS_WHEN = eINSTANCE.getTransition_HasWhen();

    /**
     * The meta object literal for the '<em><b>When</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__WHEN = eINSTANCE.getTransition_When();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__TIME = eINSTANCE.getTransition_Time();

    /**
     * The meta object literal for the '<em><b>Timeout</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__TIMEOUT = eINSTANCE.getTransition_Timeout();

    /**
     * The meta object literal for the '<em><b>Has Signal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__HAS_SIGNAL = eINSTANCE.getTransition_HasSignal();

    /**
     * The meta object literal for the '<em><b>Signal</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TRANSITION__SIGNAL = eINSTANCE.getTransition_Signal();

  }

} //StateMachinePackage
