/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.assa.sm.stateMachine;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Assignation</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link dk.sdu.mmmi.assa.sm.stateMachine.VarAssignation#getVariable <em>Variable</em>}</li>
 *   <li>{@link dk.sdu.mmmi.assa.sm.stateMachine.VarAssignation#getExpression <em>Expression</em>}</li>
 * </ul>
 *
 * @see dk.sdu.mmmi.assa.sm.stateMachine.StateMachinePackage#getVarAssignation()
 * @model
 * @generated
 */
public interface VarAssignation extends Statement
{
  /**
   * Returns the value of the '<em><b>Variable</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Variable</em>' reference.
   * @see #setVariable(VarDefinition)
   * @see dk.sdu.mmmi.assa.sm.stateMachine.StateMachinePackage#getVarAssignation_Variable()
   * @model
   * @generated
   */
  VarDefinition getVariable();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.assa.sm.stateMachine.VarAssignation#getVariable <em>Variable</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Variable</em>' reference.
   * @see #getVariable()
   * @generated
   */
  void setVariable(VarDefinition value);

  /**
   * Returns the value of the '<em><b>Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Expression</em>' containment reference.
   * @see #setExpression(Expression)
   * @see dk.sdu.mmmi.assa.sm.stateMachine.StateMachinePackage#getVarAssignation_Expression()
   * @model containment="true"
   * @generated
   */
  Expression getExpression();

  /**
   * Sets the value of the '{@link dk.sdu.mmmi.assa.sm.stateMachine.VarAssignation#getExpression <em>Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Expression</em>' containment reference.
   * @see #getExpression()
   * @generated
   */
  void setExpression(Expression value);

} // VarAssignation
