/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.mmmi.assa.sm.stateMachine.impl;

import dk.sdu.mmmi.assa.sm.stateMachine.MaxExecutionTime;
import dk.sdu.mmmi.assa.sm.stateMachine.StateMachinePackage;

import org.eclipse.emf.ecore.EClass;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Max Execution Time</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class MaxExecutionTimeImpl extends SafetyPropertyImpl implements MaxExecutionTime
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MaxExecutionTimeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return StateMachinePackage.Literals.MAX_EXECUTION_TIME;
  }

} //MaxExecutionTimeImpl
